### ISSUE TITLE
Jumbled audio

### ISSUE THREAD

**Issue by livlab** [nprapps/barkedu#142]
Getting jumbled audio on this slide. I refreshed the assets but i'm still hearing jumbled audio after playing 2 or 3 seconds. Tested on latest Chrome, OS X.

![screenshot 2015-02-18 12 45 20](https://cloud.githubusercontent.com/assets/1936365/6253016/579e7508-b76c-11e4-93cd-2cd4683f3064.png)

**Comment by livlab** [comment]
slide is /bility3

I just downloaded the repo and assets and tried it and did not encounter the jumbled audio. Might have been just my chrome cache being weird with staging url.

**Comment by TylerFisher** [comment]
Yeah, I'm struggling to replicate this. Closing, will reopen if we see it again.
