### ISSUE TITLE
Communicating progress and status

### ISSUE THREAD

**Issue by lindamood** [nprapps/barkedu#63]
how do communicate the length of the project. how many screens are there in this story?
- pagination
- page numbers
- progress bar
  etc...

**Comment by lindamood** [comment]
do we want to do a sketching session? 

look for patterns in different slide scenarios (slideshow, presentation, pagination)

**Comment by TylerFisher** [comment]
Two parallel branches, one for an animating bar and one for an updating "X of total slides" count

**Comment by TylerFisher** [comment]
@lindamood and I talked and seem to think the bar is the better option, but want to user test.

**Comment by TylerFisher** [comment]
Feel like we have a working version of this. Will open tickets further as needed.
